language: node_js
node_js:
- 14
script:
  - yarn lint
  - yarn test
cache: yarn
deploy:
  provider: heroku
  api_key:
    secure: SORAvzJWs5I//ltvm9SCV3PdKiWtztOdAcA174i1u5Qr7ATflXgT3TdJVnb4mJbf6bW6/ZR+kK8gohLoMsGzXvKE63kbvYatjfZyPLd5piKu5NgS+YtrdXHYM/q/fjykHhyhqiVbJHEvpiSzEN/5lYP+rZF1y2kTyNeLOh5nhLiCO+kTEXh1QQvXEstdyIYsKqF7Kp5vQwwiRJq9AmzERMXKb61Kkt/cIUOGXufwnXVniTG3IzpLg2RDyUFq2jEK6LOR1liRN2d53RJw2R8Img7aWmx7FucU694mH4QgskSsCNzHzPktIBu17FjMwU3LKJnc07tcUJMx3J+Lu6EubGM4adbwULVOVzV9hDiXFLKv0VkN/cYVuwf78jdBZEuzAHur2meLlfqOkzbsFU14mTjfKYsu5sWZLmoq/eWR5mYcIWrxq1YUDMeN4lKvIS7hQ7kt6cG/G6W9Ocd6jMxkpKLqq8TOH8oRi3phGSB23ZqK/bJT7pk4mCQEuX4Z+icwD3T4GwOm80MiGT8PmCjYzRAAr7puMNZjfK1Yqolc0wCP6iPyXLOr7/rW21o3yls9xfb8l38H+3vcspVRxpRmxFBVy3FUKR4cSgiFqySC+4Y0hRCDrtwlYWzlfBoVipcG8sWHA0bSh7pCzVyLOx9G8mCDeDTJI+kn8mulAikfTiE=
  app: asteffey-url-shortener
  on:
    repo: asteffey/fcc-url-shortener-microservice
  skip_cleanup: true
